# Dockerfile for PeerJS Server
FROM node:14

WORKDIR /usr/src/app

# Globally install PeerJS server
RUN npm install -g peer

# Expose only PeerJS port
EXPOSE 9000

# Start PeerJS server
CMD ["peerjs", "--port", "9000", "--key", "peerjs"]
